### PR TITLE
add separate ssh credentials for updater

### PR DESCRIPTION
**Pull request by Stricted**

### CODE REVIEW

**Comment by harryyoud** [comment]
I'm going to merge this either tonight or tomorrow, as I'd like to add the check for defined variables alongside it. 

Also need to actually make the command work, which it doesn't currently (something to do with the $BuildDate part I believe). May have to make a new variable for this.

**Comment by Stricted** [comment]
yep the $BuildDate is in the wrong format, it has to be in the format `2017-03-16` but in $BuildDate its `20170316`

**Comment by Stricted** [comment]
@harryyoud 
i added checks for variable existance and switches it from ssh to curl
the lineageos_updater has an api so why not using it :)

**Comment by Stricted** [comment]
i tested it now, works beautifuly

**Comment by harryyoud** [comment]
Does the curl API not require a build time/date?

**Comment by Stricted** [comment]
nope, that will be set automatically to the time when you added it to the updater
see https://github.com/LineageOS/lineageos_updater/blob/master/app.py#L146 and https://github.com/LineageOS/lineageos_updater/blob/master/database.py#L10

**Pull request merged**
